
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: ^(src/core|src/worker)

  - repo: local
    hooks:
      - id: eslint
        name: lint
        language: node
        entry: npm --prefix src/gui run lint_and_format
        files: ^src/gui
        types_or: [javascript, jsx, ts, tsx, vue]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
