
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    files: '^src/core'
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: eslint
        name: lint
        language: node
        entry: npm --prefix src/gui run lint
        files: ^src/gui
        types_or: [javascript, jsx, ts, tsx]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
