[project]
name = "taranis-ng-worker"
description = "Taranis-NG Queue Worker"
readme = "README.md"
license = {file = "LICENSE.md"}
maintainers = [{ name = "AIT", email = "benjamin.akhras@ait.ac.at" }]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Framework :: Celery",
    "Topic :: Security",
]
requires-python = ">=3.11"
dependencies = [
    # Core
    "celery==5.3.1",
    "click==8.1.6",
    "python-dotenv==1.0.0",
    "pydantic",
    "requests==2.31.0",
    # Collector
    "beautifulsoup4==4.12.2",
    "trafilatura==1.6.1",
    "feedparser==6.0.10",

    # Publisher
    "pymisp==2.4.173",
    "paramiko==3.2.0",
    "python-gnupg==0.5.1",
    "tweepy==4.14.0",

    # Presenters
    "weasyprint==59.0",

    # Bots
    "torch",
    "ioc-finder",
    "ioc-fanger",
    "spacy==3.6.0",
    "transformers==4.31.0",
    "sentencepiece==0.1.99",
    "py3langid==0.2.2",
    "polyfuzz==0.4.0",
    "nltk==3.8.1",
    "sentence-transformers==2.2.2",
    "keybert==0.7.0",
    "taranis-story-clustering==0.4.7",
    "xx_ent_wiki_sm @ https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.6.0/xx_ent_wiki_sm-3.6.0-py3-none-any.whl",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["black", "pytest", "pytest-celery", "watchdog", "build", "wheel", "setuptools", "setuptools_scm"]

[project.urls]
"Source Code" = "https://github.com/ait-cs-IaaS/Taranis-NG"

[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"
root = "../.."

[tool.black]
line-length = "142"
target-version = ["py311"]


[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*_app_ctx_stack.*:DeprecationWarning",
    "ignore::DeprecationWarning"
]
