version: "3.9"

services:
  database:
    image: "postgres:${POSTGRES_TAG:-14-alpine}"
    # ports:
    # - 6543:5432
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      POSTGRES_DB: "${DB_DATABASE:-taranis}"
      POSTGRES_USER: "${DB_USER:-taranis}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: ["postgres", "-c", "shared_buffers=${DB_SHARED_BUFFERS:-64MB}", "-c", "max_connections=${DB_MAX_CONNECTIONS:-1000}"]
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER:-taranis} -d ${DB_DATABASE:-taranis}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - "database_data:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  core:
    depends_on:
      database:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-core:${TARANIS_NG_TAG:-latest}"
    ports:
      - "${TARANIS_NG_CORE_PORT:-8081}:80"
    environment:
      DB_URL: "${DB_URL:-database}"
      DB_DATABASE: "${DB_DATABASE:-taranis}"
      DB_USER: "${DB_USER:-taranis}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_POOL_SIZE: 100
      DB_POOL_RECYCLE: 300
      DB_POOL_TIMEOUT: 5

      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      TARANIS_NG_AUTHENTICATOR: "${TARANIS_NG_AUTHENTICATOR:-database}"
      WORKERS_PER_CORE: "1"
      WEB_CONCURRENCY: "1"

      CVE_UPDATE_FILE: "${CVE_UPDATE_FILE:-/data/cve_dictionary.xml}"
      CPE_UPDATE_FILE: "${CPE_UPDATE_FILE:-/data/cpe_dictionary.xml}"
      PRE_SEED_PASSWORD_ADMIN: "${PRE_SEED_PASSWORD_ADMIN:-admin}"
      PRE_SEED_PASSWORD_USER: "${PRE_SEED_PASSWORD_USER:-user}"
      SECRET_KEY: "${API_KEY}"
      API_KEY: "${API_KEY}"
      DEBUG: "${DEBUG:-False}"
    volumes:
      - "core_data:/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bots:
    depends_on:
      core:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-bots:${TARANIS_NG_TAG}"
    environment:
      API_KEY: "${API_KEY}"
      TARANIS_NG_CORE_URL: "http://core"
      TARANIS_NG_CORE_SSE: "http://core/sse"
      WORKERS_PER_CORE: "1"
      WEB_CONCURRENCY: "1"
      DEBUG: "${DEBUG:-False}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  collectors:
    depends_on:
      core:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-collectors:${TARANIS_NG_TAG}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "${API_KEY}"
      WORKERS_PER_CORE: "1"
      WEB_CONCURRENCY: "1"
      DEBUG: "${DEBUG:-False}"
    volumes:
      - "collector_storage:/app/storage"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  presenters:
    depends_on:
      core:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-presenters:${TARANIS_NG_TAG}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "${API_KEY}"
      WORKERS_PER_CORE: "1"
      WEB_CONCURRENCY: "1"
      DEBUG: "${DEBUG:-False}"
    volumes:
      - "presenters_templates:/app/templates"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  publishers:
    depends_on:
      core:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-publishers:${TARANIS_NG_TAG}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "${API_KEY}"
      WORKERS_PER_CORE: "1"
      WEB_CONCURRENCY: "1"
      DEBUG: "${DEBUG:-False}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  gui:
    depends_on:
      - "core"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-gui:${TARANIS_NG_TAG}"
    ports:
      - "${TARANIS_NG_PORT:-8080}:80"
    environment:
      NGINX_WORKERS: "4"
      NGINX_CONNECTIONS: "16"
      VITE_TARANIS_NG_URL: "${TARANIS_NG_HTTPS_URI:-taranis}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  database_data:
  core_data:
  presenters_templates:
  collector_storage:
