[project]
name = "taranis-ng-core"
description = "Taranis-NG Core"
readme = "README.md"
license = {file = "LICENSE.md"}
maintainers = [{ name = "AIT", email = "benjamin.akhras@ait.ac.at" }]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Framework :: Flask",
    "Topic :: Security",
]
requires-python = ">=3.11"
dependencies = [
    "Flask",
    "Flask-Cors",
    "Flask-JWT-Extended",
    "Flask-Migrate",
    "flask-restx",
    "Flask-SQLAlchemy",

    "click",
    "celery",
    "SQLAlchemy==1.4.40",
    "pydantic-settings",
    "python-dotenv",
    "gunicorn",
    "psycogreen",
    "psycopg2",
    "swagger-ui-py",
    "requests",
    "authlib",
    "sseclient",
]
dynamic = ["version"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["core", "."]

[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"
root = "../.."

[project.optional-dependencies]
dev = ["black", "flake8", "pytest", "pytest-celery", "sqlalchemy-stubs", "schemathesis", "build", "wheel", "setuptools", "setuptools_scm"]

[project.urls]
"Source Code" = "https://github.com/ait-cs-IaaS/Taranis-NG"

[tool.black]
line-length = "142"
target-version = ["py311"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*_app_ctx_stack.*:DeprecationWarning",
    "ignore::DeprecationWarning"
]
