[project]
name = "taranis-ng_core"
description = "Taranis-NG Core"
version = "0.2.0"
readme = "README.md"
license = {file = "LICENSE.md"}
maintainers = [{ name = "AIT", email = "benjamin.akhras@ait.ac.at" }]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Framework :: Flask",
    "Topic :: Security",
]
requires-python = ">=3.10"
dependencies = [
    "Flask",
    "Flask-Cors",
    "Flask-JWT-Extended",
    "Flask-Migrate",
    "flask-restx",
    "Flask-SQLAlchemy",

    "click",
    "celery",
    "SQLAlchemy==1.4.40",
    "pydantic-settings",
    "python-dotenv",
    "gunicorn",
    "psycogreen",
    "psycopg2",
    "swagger-ui-py @ https://github.com/b3n4kh/swagger-ui-py/releases/download/23.6.15/swagger-ui-py-23.6.15.tar.gz",
    "requests"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["core", "."]

[project.optional-dependencies]
dev = ["black", "pytest", "pytest-celery", "sqlalchemy-stubs", "schemathesis"]

[project.urls]
"Source Code" = "https://github.com/ait-cs-IaaS/Taranis-NG"

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = "142"
target-version = ["py38","py310"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*_app_ctx_stack.*:DeprecationWarning",
    "ignore::DeprecationWarning"
]