name: Worker Docker image

on:
  push:
    paths:
    - 'src/worker/**'
    - 'docker/Dockerfile.worker'
    branches:
    - master
    - awake

permissions:
  packages: write

jobs:
  build:
    name: build docker
    runs-on: ubuntu-22.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get ghcr owner repository
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push worker image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile.worker
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-worker:latest
            ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-worker:${{ github.ref_name }}
