name: linting

on:
  workflow_dispatch:
  pull_request:

jobs:
  black:
    name: run black linter
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: lint with black
        uses: rickstaa/action-black@v1
        with:
          black_args: "src --check"
          fail_on_error: false

  eslint:
    name: eslint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm --prefix src/gui ci
      - name: lint with eslint
        run: npm --prefix src/gui run lint_and_format
